import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import JSZip from "jszip";
import path from "path";
import { put } from "@vercel/blob";

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);

    if (!session || !session.user?.id) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const userId = session.user.id;
    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) {
      return NextResponse.json({ message: "No backup zip file provided. Make sure to upload a valid .zip generated by TradeSync." }, { status: 400 });
    }

    // 1. Read the Zip Buffer
    const buffer = Buffer.from(await file.arrayBuffer());
    const zip = await JSZip.loadAsync(buffer);

    // 2. Locate and Parse trades.json
    const tradesJsonFile = zip.file("trades.json");
    if (!tradesJsonFile) {
      return NextResponse.json({ message: "Invalid backup file: Could not find trades.json inside the .zip archive." }, { status: 400 });
    }

    const tradesJsonString = await tradesJsonFile.async("string");
    let tradesData = [];
    try {
      tradesData = JSON.parse(tradesJsonString);
      if (!Array.isArray(tradesData)) throw new Error("Not an array");
    } catch (e) {
      return NextResponse.json({ message: "Invalid backup file: trades.json is corrupted or not a valid JSON array." }, { status: 400 });
    }

    if (tradesData.length === 0) {
      return NextResponse.json({ message: "The backup json is empty. There are no trades to restore." }, { status: 400 });
    }

    // 3. Extract and Restore Media Files to Vercel Blob
    const newUrlMap: Record<string, string> = {};

    if (process.env.BLOB_READ_WRITE_TOKEN) {
      const imagesFolder = zip.folder("images");
      if (imagesFolder) {
        const filePathsInImages = Object.keys(zip.files).filter(name => name.startsWith("images/") && !zip.files[name].dir);
        for (const zipPath of filePathsInImages) {
          const fileObj = zip.file(zipPath);
          if (fileObj) {
            try {
              const rawFileName = path.basename(zipPath);
              const fileBuffer = await fileObj.async("nodebuffer");
              const blob = await put(`tradesync/${rawFileName}`, fileBuffer, { access: 'public' });
              newUrlMap[rawFileName] = blob.url;
            } catch (e) {
              console.error(`Failed to restore image: ${zipPath}`, e);
              // non-fatal — continue without this image
            }
          }
        }
      }
    }

    // 4. Update the Database
    // Note: We perform this in a transaction. Delete all trades for the user, then inject the backup exactly as they were.
    await prisma.$transaction(async (tx) => {
      // Safely delete existing active trades for this user.
      await tx.trade.deleteMany({
        where: { userId: userId }
      });

      // Prepare backup objects to match Prisma schema constraints.
      // Re-map the image URLs carefully since they've mutated.
      const inserts = tradesData.map(t => {
        let finalImageUrls = t.imageUrls;
        if (finalImageUrls && Object.keys(newUrlMap).length > 0) {
          try {
            const parsed = JSON.parse(finalImageUrls);
            const mapped = parsed.map((oldUrl: string) => {
              const oldFn = path.basename(oldUrl);
              return newUrlMap[oldFn] || oldUrl;
            });
            finalImageUrls = JSON.stringify(mapped);
          } catch(e) {}
        }
        
        return {
          id: t.id,
          userId: userId, 
          instrument: t.instrument,
          direction: t.direction,
          date: new Date(t.date),
          session: t.session || null,
          entryPrice: t.entryPrice,
          exitPrice: t.exitPrice,
          pnl: t.pnl,
          setup: t.setup || null,
          emotions: t.emotions || null,
          notes: t.notes || null,
          imageUrls: finalImageUrls || null,
          contractSize: t.contractSize || null,
          rating: t.rating || null,
          createdAt: t.createdAt ? new Date(t.createdAt) : new Date(),
          updatedAt: t.updatedAt ? new Date(t.updatedAt) : new Date(),
        };
      });

      // In sqlite/postgres createMany allows pre-defined generic IDs.
      await tx.trade.createMany({
        data: inserts,
        skipDuplicates: true,
      });
    });

    return NextResponse.json({ message: "Successfully restored all trades and media files." }, { status: 200 });

  } catch (error: any) {
    console.error("Restore handler failed:", error);
    return NextResponse.json({ message: "Critical Server Error during restore sequence.", details: error?.message || "" }, { status: 500 });
  }
}
